/**
 * Script to get a card's encrypted data (PAN and CVC) from the Rain API
 * 
 * Usage:
 *   CARD_ID="94af0c92-5c11-4d0d-889c-f9093819cb18" SESSION_ID="your-session-id" npm run rain:get-secrets
 * 
 * Note: SessionId is an encrypted session ID generated by the user requesting the encrypted data.
 * This is typically generated through the Rain frontend or user authentication flow.
 */

import { getCardSecrets } from '../lib/rain-api';

async function main() {
  const cardId = process.env.CARD_ID;
  const sessionId = process.env.SESSION_ID;

  if (!cardId) {
    console.error('❌ Error: CARD_ID environment variable is required');
    console.error('\nUsage:');
    console.error('  CARD_ID="your-card-id" SESSION_ID="your-session-id" npm run rain:get-secrets');
    process.exit(1);
  }

  if (!sessionId) {
    console.error('❌ Error: SESSION_ID environment variable is required');
    console.error('\nUsage:');
    console.error('  CARD_ID="your-card-id" SESSION_ID="your-session-id" npm run rain:get-secrets');
    console.error('\nNote: SessionId is an encrypted session ID generated by the user.');
    console.error('This is typically obtained through the Rain frontend or user authentication flow.');
    process.exit(1);
  }

  console.log(`Fetching encrypted data for card ID: ${cardId}\n`);

  try {
    const secrets = await getCardSecrets(cardId, sessionId);

    console.log('✅ Card secrets retrieved successfully!');
    console.log('\nEncrypted Card Data:');
    console.log(JSON.stringify(secrets, null, 2));

    console.log('\n📋 Secrets Summary:');
    console.log(`  Encrypted PAN:`);
    console.log(`    IV: ${secrets.encryptedPan.iv}`);
    console.log(`    Data: ${secrets.encryptedPan.data.substring(0, 50)}... (truncated)`);
    
    console.log(`  Encrypted CVC:`);
    console.log(`    IV: ${secrets.encryptedCvc.iv}`);
    console.log(`    Data: ${secrets.encryptedCvc.data.substring(0, 50)}... (truncated)`);

    console.log('\n💡 Note:');
    console.log('  - The encrypted data needs to be decrypted using the user\'s session key');
    console.log('  - This data should be handled securely and not logged in production');
    console.log('  - The SessionId is required and must be generated through the proper user authentication flow');
  } catch (error) {
    console.error('\n❌ Error fetching card secrets:');
    console.error(error);
    process.exit(1);
  }
}

main();

